import rootReducer from "./reducers";

export enum ReduxActions {
    SET_FETCHED_TOPICAL_HOMEWORK = "SET_FETCHED_TOPICAL_HOMEWORK",
    SET_FETCHED_ARCHIVE_HOMEWORK = "SET_FETCHED_ARCHIVE_HOMEWORK",
    // APPEND_FETCHED_ARCHIVE_HOMEWORK = "APPEND_FETCHED_ARCHIVE_HOMEWORK",
    SET_SELECTED_HOMEWORK_TYPE = "SET_SELECTED_HOMEWORK_TYPE",
    SET_END_REACHED = "SET_END_REACHED",
    RESET_FETCHED_HOMEWORK = "RESET_FETCHED_HOMEWORK",

    SET_FETCHED_GROUPS = "SET_FETCHED_GROUPS",
    SET_GROUP_INFO = "SET_GROUP_INFO",
    SET_CURRENT_GROUP_ID = "SET_CURRENT_GROUP_ID",
    SET_GROUPS_LIMIT_REACHED = "SET_GROUPS_LIMIT_REACHED",
    DELETE_SAVED_GROUP = "DELETE_SAVED_GROUP"
}

export type AppState = ReturnType<typeof rootReducer>;